from . import test_sample_transfer_wizard
from . import test_sample_split_wizard
from . import test_sample_merge_wizard
from . import test_sample_scrap_wizard
from . import test_sample_return_wizard
from . import test_sample_receive_wizard
from . import test_sample_bulk_receive_wizard
from . import test_sample_bulk_receive_from_list_wizard
from . import test_sample_bulk_transfer_wizard
from . import test_sample_bulk_return_wizard
from . import test_sample_bulk_scrap_wizard
from . import test_sample_confirm_shipment_wizard
from . import test_sample_confirm_pickup_wizard
