

{
    "name": "Test Sample Tracking",
    "version": "18.0.1.1.0",
    "author": "Edvin Nyberg",
    "license": "OPL-1",
    "category": "Services",
    "website": "https://www.intertek.com/",
    "summary": "Track test samples from receipt through testing to return or disposal",
    "depends": ["mail", "base", "sale", "project"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/courier_data.xml",
        "views/test_sample_location_views.xml",
        "views/test_sample_courier_views.xml",
        "views/test_sample_transfer_views.xml",
        "views/test_sample_transfer_wizard_views.xml",
        "views/test_sample_split_wizard_views.xml",
        "views/test_sample_merge_wizard_views.xml",
        "views/test_sample_scrap_wizard_views.xml",
        "views/test_sample_return_wizard_views.xml",
        "views/test_sample_confirm_shipment_wizard_views.xml",
        "views/test_sample_confirm_pickup_wizard_views.xml",
        "views/test_sample_bulk_transfer_wizard_views.xml",
        "views/test_sample_bulk_return_wizard_views.xml",
        "views/test_sample_bulk_scrap_wizard_views.xml",
        "views/test_sample_bulk_receive_wizard_views.xml",
        "views/test_sample_bulk_receive_from_list_wizard_views.xml",
        "views/test_sample_receive_wizard_views.xml",
        "views/test_sample_line_views.xml",
        "views/test_sample_views.xml",
        "views/sale_order_views.xml",
        "views/res_config_settings_views.xml",
        "report/test_sample_shipping_label.xml",
        "report/test_sample_serial_labels.xml",
        "menu/menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
